inmakes_ecommerse/cart/urls.py
from django.urls import path
app_name='cart'
from cart import views

urlpatterns = [
    path('cart_id/',views._cart_id,name='_cart_id'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('cart_remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
    ]

inmakes_ecommerse/ecommproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop',include('shop.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inmakes_ecommerse/searchapp/urls.py
from django.urls import path
from .import views
app_name='searchapp'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),

]

inmakes_ecommerse/shop/urls.py
from django.urls import path
#app_name='shop'
from shop import views

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail,name='prodCatdetail'),
]

inmakes_ecommerse/cart/models.py
from django.db import models
from shop .models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=225,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}' .format(self.cart_id)


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return '{}' .format(self.product)

inmakes_ecommerse/searchapp/models.py
from django.db import models

# Create your models here.

inmakes_ecommerse/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=220,unique=True)
    slug=models.SlugField(max_length=220,unique=True)
    discription=models.TextField(blank=True)
    image=models.ImageField(upload_to='catgory',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('product_by_category',args=[self.slug])

    def __str__(self):
        return self.name



class Product(models.Model):
    name=models.CharField(max_length=220,unique=True)
    slug=models.CharField(max_length=220,unique=True)
    discription = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('prodCatdetail',args=[self.category.slug,self.slug])

        def __str__(self):
            return {}.formate(self.name)

inmakes_ecommerse/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart= request.session.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product= get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item .delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

inmakes_ecommerse/searchapp/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
      query=request.GET.get('q')
      products=Product.objects.all().filter(Q(name__contains=query) | Q(discription__contains=query))
      return render(request,'search.html',{'query':query,'products':products})

inmakes_ecommerse/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
from shop.models import Category, Product


def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{"category":c_page,"products":products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{"product":product})

inmakes_ecommerse/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="discription" content="{% block metadiscription %}{% endblock %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <title>{% block titlle %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>

inmakes_ecommerse/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadiscription %}
    This is the cart page .Proceed to review your items and place the order
{% endblock %}
{% block title %}
    cart - DMOM Clothing Hub
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shoping Cart is Empty</h1>
        <br>
        <p class="text-center">Please Click <a href="{% url 'allprodCat' %}">Here</a>To continue shopping</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
      <br>
      <h1 class="text-center  my_title">Your shopping cart</h1>
      <br>
    </div>
</div>
{% endif %}
<div class="row mx_auto">

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center" >
    <table class="table my_custom_table"  >
        <thead class="my_custom_thead">
        <tr>
            <th colspan="5">
                Your Items
            </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
            <td>
                <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" width="150px" height="90px"></a>
            </td>
            <td class="text_left">
                {{cart_item.product.name}}
                <br>
                SKU:{{cart_item.product.id}}
                <br>
                Price:${{cart_item.product.price}}
                <br>
                Qty:{{cart_item.quantity}} x ${{cart_item}}
            </td>
            <td>
                ${{cart_item.sub_total}}
            </td>
            {% if cart_item.quantity < cart_item.product.stock %}
            <td>
               <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon" ></i></a><br> &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon " ></i></a> <br>&nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
            </td>
            {% else %}
             <td>
                &nbsp<a href="{% url 'cart:cart_remove' cart_item.product.id  %}" class="custom_a"><i class="fa fa-minus custom_icon" ></i></a><br> &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
             </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

  <div class="col-12 col-sm-12 col-md-6 col-lg-6 text-center">
    <table class="table_my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                Check Out
            </th>
        </tr>
        </thead>

        <tbody>

        <tr>
            <td>
                <br>
                Please review your shopping cart items before proceeding with the order payment
            </td>

        </tr>
        <tr>

            <td class="text-left">
               <br><p>TOTAL P :<strong>{{total}}</strong></p>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx_auto">
    <br><a href="{% url 'allProdCat' %}" class="btn btn-secondary btn-block my_custom_button" >Continue Shopping</a>
    </div>
  </div>
</div>
{% endblock %}

inmakes_ecommerse/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadiscription %}
{% if category %}
    {{category.description|truncatewords:155}}
{% else %}
    <h3>Welcome to DMOM clothing store where you can buy diffrent items</h3>
{% endif %}
{% endblock%}

{% block title %}
{% if category %}
    {{ category.name }}
{% else %}
    <h3> See our new collections </h3>
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my-row-class">
        <div class="mx-auto">
        <p><a href="{% url 'allProdCat' %}">collect the products</a></p>
        </div>
    </div>
</div>
{% endif %}
<div class="max-auto">
    {% if category %}
    <img  src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my title">{{category.name}}</h1>
     <P class="text-justify">{{category.discription}}</P>
</div>
{% else %}
<div>
    <img class="my-image my-image-padding" src="{% static 'image/DMOM SHOP.jpg' %}" alt="ourproduct" width="100%" height="250px"  >
</div>
<br>
<div>
    <h1 class="text-center my-title">Our product collection </h1>
    <p class="text-justify">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will
        uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometim</p>
</div>
{% endif %}
<div class="container" >
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_mrgin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text_center" style="min-width:5rem;">
            <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:170px;height:170px;"></a>
            </div>
            <div class="card_body" style="font-size:12px;padding-left:70px;">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

inmakes_ecommerse/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="footer navbar-fixed-bottom my-footer">
    <p style="margin-top:130px;" class="text-center">&copy;DMOM Clothing Hub</p>
</div>
</body>
</html>

inmakes_ecommerse/templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">


</head>
<body>
 <header>
    <a href="{% url 'allProdCat' %}"></a><img style="margin-left:590px;width:80px;heigth:90px;" src="{% static 'image/1.png' %}" alt="loginimage" >
</header>
</body>
</html>

inmakes_ecommerse/templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<script src="{% static 'pooper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>

</body>
</html>

inmakes_ecommerse/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" >
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'allProdCat' %}">All Product</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
             {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i>({{item_count}})</a>
        </li>
      {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
      </form>
    </div>
  </div>
</nav>
</body>
</html>

inmakes_ecommerse/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadiscription %}

    {{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
{% if category %}
    {{product.name}}
{% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
    <div class="row">
     <div class="col-12 col-sm-12 col-md-6 col-lg-6 text_center" >
        <div style="min_width:10rem">
            <img style="width:280px;height:310px" src="{{product.image.url}}" alt="{{product.name}}">
        </div>
     </div>

     <div class="col-12 col-sm-12 col-md-6 col-lg-6">
         <div>
             <h1 class="my_product_title">{{product.name}}</h1>
             <p>${{ product.price}}</p>
             <h2 class="my_title">Product Description</h2>
             <p class="text-justify my_prot_text">{{product.discription}}</p>
             {% if product.stock <= 0 %}
             <h3 class="text-justify my_prot_text" ><b>Out of Stock</b></h3>
             {% else %}
             <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add-to-Cart</a>
             {% endif %}
         </div>
     </div>

</div>
</div>
{% endblock %}

inmakes_ecommerse/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block metadiscription %}
    <h4>We have vayiety of products</h4>
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text_center" style="min-width:5rem;">
            <a href="{{product.get_url}}"><img class="card_img_top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:170px;height:170px;"></a>
            </div>
            <div class="card_body" style="font-size:12px;padding-left:70px;">
                <h4>{{product.name}}</h4>
                <p>{{product.price}}</p>
            </div>
        </div>
        </div>
    {% empty %}
    <div class="row mx_auto">
        <p class="text-center my_search_text">0 result found</p>
    {% endfor %}
    </div>

</div>
{% endblock %}